Convert helper scripts to YAMLScript

diff --git a/bin/rcd-new-langs b/bin/rcd-new-langs
--- a/bin/rcd-new-langs
+++ b/bin/rcd-new-langs
@@ -1,19 +1,14 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ys-0
+!ys-0
 
-set -e -u -o pipefail
+EXCLUDE =:
+  qr("[éæ:]|Languages by Feature|Programming Language|Oberon-2|Free Pascal")
 
-root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
-
-cd "$root"
-
-bin/rcd-api-list-all-langs |
-while read -r lang; do
-  re=${lang//\\/\\\\}
-  re=${re//+/\\+}
-  re=${re//\*/\\*}
-  re=${re//\(/\\\(}
-  grep -Eq "^'?$re'?: '?\." Conf/lang.yaml ||
-    echo "$lang"
-done |
-  grep -Ev '([éæ:]|Languages by Feature|Programming Language|Oberon-2|Free Pascal)' ||
-    true
+defn main():
+  when-not fs/e('Conf/lang.yaml'):
+    die: 'Not at RosettaCodeData root (Conf/lang.yaml missing)'
+  known =: set(keys(read('Conf/lang.yaml'):yaml/load))
+  raw =: bash-out('bin/rcd-api-list-all-langs')
+  each name raw:lines:
+    when-not (known.has?(name) || (name =~ EXCLUDE)):
+      say: name
